version: "3.8"

services:
  admin:
    container_name: movies_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
#    depends_on:
#      - database
#
#  database:
#    container_name: movies_admin_db
#    image: mysql:5.7.22
#    restart: always
#    environment:
#      MYSQL_DATABASE: django_admin
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - .dbdata:/var/lib/mysql
#    ports:
#      - 33066:3306
